[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ctool"
authors = [
    { name = "Timothy Brackett", email="brackett.tc@gmail.com" },
    ]
description = "A CMake wrapper and toolset"
keywords = [
    "cmake"
    ]
readme = { file = "README.md", content-type = "text/markdown" }
requires-python = ">= 3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: POSIX :: Linux",
    "Development Status :: 1 - Planning",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: The Unlicense (Unlicense)",
    "Topic :: Software Development :: Build Tools",
    "Topic :: Software Development :: Testing",
    ]

dynamic = ["version", "dependencies"]

[tool.setuptools.dynamic]
version = { attr = "ctool.__version__.VERSION" }
dependencies = { file = ["requirements.txt"] }

[project.optional-dependencies]
# development dependencies
test = [
    "pytest",
    ]

[project.scripts]
ctool = "ctool:main"
ctool-depends = "ctool.depends:main"
ctool-changed-tests = "ctool.changed_tests:main"

[project.urls]
Homepage = "https://github.com/bracketttc/ctool"
Issues = "https://github.com/bracketttc/ctool/issues"

#[tool.setuptools.package-data]
#"ctool" = ["py.typed"]

#[tool.setuptools.packages.find]
#where = ["src"]

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
    ]

[tool.coverage.report]
omit = ["tests/*"]
